# Generated by Django 4.2.30 on 2026-04-21 22:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_chosen_name', models.CharField(max_length=255)),
                ('donation_amount', models.IntegerField()),
                ('donation_payment_method', models.CharField(max_length=255)),
                ('donation_expiration', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('donor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
                ('donor_email', models.CharField(max_length=255)),
                ('donor_country', models.CharField(max_length=255)),
                ('total_donation_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('tree_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permanent_tag', models.CharField(max_length=255)),
                ('study', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('common_name_spanish', models.CharField(max_length=255)),
                ('common_name_english', models.CharField(max_length=255)),
                ('dbh', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('lat', models.CharField(max_length=255)),
                ('long', models.CharField(max_length=255)),
                ('adoption_status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='donations',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.donors'),
        ),
        migrations.AddField(
            model_name='donations',
            name='tree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.trees'),
        ),
    ]
