# Generated by Django 4.2.30 on 2026-04-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_donations_donors_trees_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donations',
            new_name='Donation',
        ),
        migrations.RenameModel(
            old_name='Donors',
            new_name='Donor',
        ),
        migrations.AlterModelOptions(
            name='trees',
            options={'verbose_name_plural': 'Trees'},
        ),
    ]
