# Generated by Django 4.2.30 on 2026-04-22 15:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_rename_donations_donation_rename_donors_donor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permanent_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('study', models.CharField(blank=True, max_length=255, null=True)),
                ('family', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('common_name_spanish', models.CharField(max_length=255)),
                ('common_name_english', models.CharField(max_length=255)),
                ('dbh', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_description', models.TextField(blank=True)),
                ('lat', models.CharField(max_length=255)),
                ('long', models.CharField(max_length=255)),
                ('adoption_status', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.donor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tree_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.tree'),
        ),
        migrations.DeleteModel(
            name='Trees',
        ),
    ]
