# Generated by Django 4.2.30 on 2026-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_tree_alter_donation_donor_id_alter_donation_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_expiration',
            new_name='expiration_date',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='donation_payment_method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='donor_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='donor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='donor_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='donor_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='tree_id',
            new_name='id',
        ),
    ]
