# Generated by Django 4.2.30 on 2026-04-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_rename_donation_amount_donation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tree',
            name='modified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
