# Generated by Django 4.2.30 on 2026-04-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_donation_number_tree_modified_tree_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='number',
            field=models.IntegerField(blank=True, default=0, help_text='This number will be added automatically. No need for any input.'),
        ),
    ]
