# Generated by Django 4.2.30 on 2026-04-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_alter_tree_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='adoption_status',
            field=models.CharField(choices=[('adoptable', 'Adoptable'), ('adopted', 'Adopted')], default='adoptable', max_length=10),
        ),
    ]
