# Generated by Django 6.0.4 on 2026-04-29 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_alter_tree_adoption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 29, 14, 0, 48, 193187, tzinfo=datetime.timezone.utc), help_text='Date is automatically set.'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_chosen_name',
            field=models.CharField(help_text='Name that will appear on the adopted tree.', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text="'Expiration Date' is automatically calculated.", null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='number',
            field=models.IntegerField(default=0, help_text="'Number' automatically calculated after entry creation."),
        ),
        migrations.AlterField(
            model_name='tree',
            name='dbh',
            field=models.CharField(help_text='Diameter at Breast Height', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.CharField(help_text='Latitude', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='long',
            field=models.CharField(help_text='Longitude', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='modified',
            field=models.TextField(blank=True, help_text="'Modified' automatically calculated after entry creation.", null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='number',
            field=models.IntegerField(blank=True, default=0, help_text="'Number' automatically calculated after entry creation."),
        ),
    ]
