# Generated by Django 6.0.4 on 2026-05-10 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_alter_donation_date_alter_donation_donor_chosen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date is automatically set.'),
        ),
    ]
