# Generated by Django 6.0.4 on 2026-05-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0010_alter_donation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='long',
        ),
        migrations.AddField(
            model_name='tree',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tree',
            name='lng',
            field=models.FloatField(default=0, help_text='Longitude'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_chosen_name',
            field=models.CharField(default='Anonymous', help_text='Name that will appear on the adopted tree.', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='trees.donor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tree_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='trees.tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.FloatField(default=0, help_text='Latitude'),
        ),
    ]
