# Generated by Django 6.0.4 on 2026-05-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0011_remove_tree_long_tree_age_tree_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.CharField(help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lng',
            field=models.CharField(help_text='Longitude'),
        ),
    ]
