# Generated by Django 6.0.4 on 2026-05-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0012_alter_tree_lat_alter_tree_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.FloatField(default=0, help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lng',
            field=models.FloatField(default=0, help_text='Longitude'),
        ),
    ]
