# Generated by Django 6.0.4 on 2026-05-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0013_alter_tree_lat_alter_tree_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='stripe_session_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
