# Generated by Django 6.0.4 on 2026-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0014_donation_currency_donation_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
