# Generated by Django 6.0.4 on 2026-05-23 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0015_donation_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
