# Generated by Django 6.0.4 on 2026-05-30 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0016_remove_donation_updated_at_tree_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='age',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='dbh',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='number',
        ),
        migrations.AddField(
            model_name='tree',
            name='tag_id',
            field=models.IntegerField(blank=True, default=0, help_text='Auto generated: scientificNameAbbreviation-permanentTag. Ex: BEEX-0000'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary Key (UUID) used for relations.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lat',
            field=models.FloatField(default=0, help_text='Latitude: XX.XXXX / -XX.XXXX'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='lng',
            field=models.FloatField(default=0, help_text='Longitude: XX.XXXX / -XX.XXXX'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='permanent_tag',
            field=models.CharField(default=1, help_text='Tree Tag Number: XXXX', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.CharField(default='XX', max_length=255),
        ),
    ]
