# Generated by Django 6.0.4 on 2026-05-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0017_remove_tree_age_remove_tree_dbh_remove_tree_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='tag_id',
            field=models.CharField(blank=True, default='XXXX-XXXX', help_text='Auto generated: scientificNameAbbreviation-permanentTag. Ex: BEEX-0000', max_length=255),
        ),
    ]
