# Generated by Django 6.0.4 on 2026-05-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0018_alter_tree_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
