# Generated by Django 6.0.4 on 2026-05-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0019_alter_tree_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Auto generated: Month, Day, Year, Time'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Auto generated: Month, Day, Year, Time'),
        ),
    ]
