# Generated by Django 6.0.4 on 2026-05-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0020_alter_tree_created_at_alter_tree_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_id',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='trees.donor'),
        ),
    ]
