# Generated by Django 6.0.4 on 2026-05-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0021_remove_donation_donor_id_alter_donation_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='dbh',
            field=models.CharField(blank=True, default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='common_name_english',
            field=models.CharField(blank=True, default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.CharField(blank=True, default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='study',
            field=models.CharField(blank=True, default='.', max_length=255),
        ),
    ]
