# Generated by Django 6.0.4 on 2026-05-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0022_tree_dbh_alter_tree_common_name_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='common_name_english',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='dbh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
