# Generated by Django 6.0.4 on 2026-05-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0023_alter_tree_common_name_english_alter_tree_dbh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
