# Generated by Django 6.0.4 on 2026-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0024_tree_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='permanent_tag',
            field=models.CharField(help_text='Tree Tag Number: XXXX. <b>Important:</b> If permanent tag is modified, the tag in the corresponding Azure picture must also be changed.', max_length=255),
        ),
        migrations.AlterField(
            model_name='tree',
            name='species',
            field=models.CharField(blank=True, help_text='<b>Important:</b> If species is modified, the taxonomy tag in the corresponding Azure picture must also be changed.', max_length=255, null=True),
        ),
    ]
