# Generated by Django 6.0.4 on 2026-06-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0025_alter_tree_permanent_tag_alter_tree_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='species_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
