# Generated by Django 6.0.4 on 2026-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0026_tree_species_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='expiration_processed',
            field=models.BooleanField(default=False),
        ),
    ]
