# Generated by Django 6.0.4 on 2026-06-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0027_donation_expiration_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='expired_tree_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
