# Generated by Django 6.0.4 on 2026-06-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0028_donation_expired_tree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='searchable_donor_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='searchable_tree_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='expired_tree_id',
            field=models.CharField(blank=True, default='', help_text='Automatically set upon tree expiration.', max_length=255),
        ),
        migrations.AlterField(
            model_name='donation',
            name='tree_id',
            field=models.OneToOneField(blank=True, help_text='Tag ID of the adopted tree. Automatically set upon adoption.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation', to='trees.tree'),
        ),
    ]
