# Generated by Django 6.0.4 on 2026-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0029_donation_searchable_donor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='reserve_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
