# Generated by Django 6.0.4 on 2026-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0030_tree_reserve_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='species_description',
            field=models.TextField(blank=True, default='', help_text='Species facts for Wix page. <b>Important:</b> Seperated by semi-colon. Ex: Fact1; Fact2; Fact3;'),
        ),
    ]
