# Generated by Django 6.0.4 on 2026-06-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0031_alter_tree_species_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='certificate_sent',
            field=models.BooleanField(default=False),
        ),
    ]
